### ISSUE TITLE
How to receive event?

### ISSUE THREAD

**Issue by alopatindev** [neovim/neovim-ruby#102]
```ruby
client = Neovim.attach_unix('nvim.sock')
client.subscribe('event')
```

In nvim I do `:call rpcnotify(0, 'event')`

How do I know that the event has happened?

I wish the API was something like `client.subscribe('event', |args| print(args))`.

I see no trace of anything similar to [`next_message()`](https://pynvim.readthedocs.io/en/latest/api/nvim.html#pynvim.api.Nvim.next_message) or [`run_loop(request_cb = None, notification_cb = lambda event, args: print(args))`](https://pynvim.readthedocs.io/en/latest/api/nvim.html#pynvim.api.Nvim.run_loop) in the public API docs.

Public method [from_event_loop](https://rubydoc.info/github/neovim/neovim-ruby/Neovim%2FClient.from_event_loop) takes private type [`EventLoop`](https://rubydoc.info/github/neovim/neovim-ruby/Neovim/EventLoop) as argument, which is constructed in the [attach](https://github.com/neovim/neovim-ruby/blob/25560e46e2d0027c8c6e4b000b16e9376d8253c5/lib/neovim.rb#L74), but I see nothing like public API for `EventLoop::read`.

**Comment by alopatindev** [comment]
Works, thanks!

However Session is [marked private](https://rubydoc.info/github/neovim/neovim-ruby/Neovim/Session). Will it become public at some point?

**Comment by alexgenco** [comment]
> Will it become public at some point?

No plans at the moment. TBH I'm not really actively working on this library anymore, just bugfixes and stuff. So if this were to be made public (possibly on the `Client` class, with an interface like you suggested), it would have to come from outside contributors.
