### ISSUE TITLE
neovim-ruby-host has incorrect generated path to ruby binary

### ISSUE THREAD

**Issue by pjgoodall** [neovim/neovim-ruby#103]
The first 6 lines of the generated gem `neovim-ruby-host ` prepare an invalid path to the ruby binary - which causes the execution of the gem to fail. There may be other related configuration errors I have not found.

when I first ran `:checkhealth provider` in nvim I had this error:

``` text
Ruby provider (optional) ~
- Ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim
```
I  installed ruby using `mamba install -c conda-forge ruby compilers`
i installed the neovim gem:  `gem install neovim`

Both ruby and neovim-ruby-host are on my path, and on the neovim internal path:
```
❯ which ruby
/home/peterg/miniconda3/bin/ruby
❯ which neovim-ruby-host
/home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host
```
Initially the gem was not finding ruby on either path, so I added it to the neovim `config/options.lua` file - much like is standard with python:

``` lua
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

vim.g.python3_host_prog = "/home/peterg/miniconda3/envs/pynvim/bin/python"
vim.g.ruby_host_prog = "/home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host"
```

After this within nvim if I execute `:checkhealth provider` - I get the following changed error output:

``` text
Ruby provider (optional) ~
- Ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Host: /home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host
- ERROR Command error (job=15, exit code 127): `'/home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host' --version` (in '/home/peterg')
  stderr: /home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host: 6: exec: /home/peterg/miniconda3/share/rubygems/bin/ruby: not found
- ERROR Failed to run: /home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host --version
  - ADVICE:
    - Report this issue with the output of: 
    - /home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host --version
```

The first 16 lines of the neovim-ruby-host script:
``` sh
#!/bin/sh
# -*- ruby -*-
_=_\
=begin
bindir="${0%/*}"
exec "$bindir/ruby" "-x" "$0" "$@"
=end
#!/home/peterg/miniconda3/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'neovim' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'
```
The `bindir=`  expression appears to expect the ruby binary to be in the same directory as the script. 

If I delete the first 6 lines of the file, the ruby provider passes `neovim :checkhealth provider`

``` text
Ruby provider (optional) ~
- Ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Host: /home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host
- OK Latest "neovim" gem is installed: 0.9.1
```
I have never been a ruby developer - so this is about the limit of my diagnostic capabilities.

**Comment by pjgoodall** [comment]
```
❯ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
❯ conda --version
conda 23.11.0
```

```
❯ nvim --version
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/nvim/parts/nvim/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by pjgoodall** [comment]
If in nvim,  I run `:echo system('which ruby')`  
I get the following: `/home/peterg/miniconda3/bin/ruby`

`:echo system('which neovim-ruby-host')`  
gives me: `/home/peterg/miniconda3/share/rubygems/bin/neovim-ruby-host`

**Comment by alexgenco** [comment]
I don't really know anything about this package manager you're using, but this seems like an issue with your local Ruby installation. That `neovim-ruby-host` wrapper script is generated by [RubyGems](https://github.com/jbourassa/ruby/blob/b2e848193aad70cffd972b15fcc6cbf6be843d94/lib/rubygems/installer.rb#L994-L1001), not by neovim-ruby. Do other ruby gems with bundled executables have similar issues? You could try `bundler` for instance

**Comment by pjgoodall** [comment]
my apologies. 
I'm a  new user of neovim and lazyvim - which environments have so many dependencies that its is a nightmare to check the configuration errors. Both Ruby and Python each have many ways of configuring them.  I'm not a Ruby user.  So I have gone as far as I reasonably can with this. 
Thanks for your time...

**Comment by pjgoodall** [comment]
The same errors when ruby install using  `apt install ruby ruby-dev` Which is bog-standard.
see https://github.com/andrewrothstein/ansible-ruby
I am installing onto a clean debian-bookworm virtual host.
I do not know how to get any further with this.  Cost me most of a day.
Where do I report this?

**Comment by pjgoodall** [comment]
same errors when ruby install using  `apt install ruby ruby-dev` Which is bog-standard.
see https://github.com/andrewrothstein/ansible-ruby
I am installing onto a clean debian-bookworm virtual host.
I do not know how to get any firther with this.

**Comment by pjgoodall** [comment]
Testing gem infrastructure:

```
debian1% sudo gem install json
Fetching json-2.7.1.gem
Building native extensions. This could take a while...
Successfully installed json-2.7.1
Parsing documentation for json-2.7.1
Installing ri documentation for json-2.7.1
Done installing documentation for json after 0 seconds
1 gem installed
```
test of json gem:

``` ruby
require 'json'

puts "JSON Gem Test"
puts "Ruby Version: #{RUBY_VERSION}"
puts "JSON Version: #{JSON::VERSION}"

json = JSON.generate({ message: 'Hello, world!' })
puts "Generated JSON: #{json}"
```

output:

``` text
debian1% ruby test_gem.rb 
JSON Gem Test
Ruby Version: 3.1.2
JSON Version: 2.7.1
Generated JSON: {"message":"Hello, world!"}
```

**Comment by pjgoodall** [comment]
The problem seems to be that I should have installed the gem using become: in ansbile. 
Not installed with correct permissions...
