### ISSUE TITLE
still using system ruby

### ISSUE THREAD

**Issue by 9mm** [neovim/neovim-ruby#104]
Hey, I have searched around for a few hours and I am out of ideas. Neovim keeps using system ruby even though it's properly seeing my provider:

neovim config:

```lua
vim.g.ruby_host_prog = "/Users/zesty/.rbenv/shims/neovim-ruby-host"
```

Terminal output to test:

```
rbenv whence neovim-ruby-host
3.3.1

whence neovim-ruby-host
/Users/zesty/.rbenv/shims/neovim-ruby-host
```

Output of `:checkhealth`

```
Ruby provider (optional) ~
- Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
- Host: /Users/zesty/.rbenv/shims/neovim-ruby-host
- OK Latest "neovim" gem is installed: 0.9.1
```

more output from terminal

```
➜  ~ rbenv versions
  system
* 3.3.1 (set by /Users/zesty/.rbenv/version)
```

Do you know why its still using system ruby instead of 3.3.1?

**Comment by 9mm** [comment]
Hmm... this actualy works inside `nvim` but not `neovide`...

**Comment by justinmk** [comment]
> Hmm... this actualy works inside `nvim` but not `neovide`...

@9mm probably because `nvim` inherits your shell configuration, while a GUI does not?
