### ISSUE TITLE
Move to Neovim org?

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim-ruby#53]
@alexgenco Given that this is one of the most well-maintained API clients and it is part of the core documentation and runtime, would you be interested in transferring it to the https://github.com/neovim/ org ? 

You would of course continue to have full admin rights there. Essentially nothing would change except "user perception".

If you'd rather not that's fine too!

**Comment by alexgenco** [comment]
I don't see any reason why not... we'd probably want to rename the repo to `ruby-client` as well for consistency I take it.

It looks like I can request the transfer even though I don't yet have repo creation access, so I'll do that. Then we can rename once you approve.

**Comment by alexgenco** [comment]
Scratch that, I can't even request the transfer without repo creation permissions.

**Comment by justinmk** [comment]
Invited  you, if you visit https://github.com/neovim and accept then you should have repo-creation ability.

**Comment by alexgenco** [comment]
Alright it's moved over. Looks like you'll have to do the rename.

It prompted me to grant teams access to the repo, including teams like "core", "go-client", "marvim", etc. I didn't invite any for now, but I assume we can invite as-needed.

**Comment by justinmk** [comment]
Ok, great!  I just changed your role to "Admin", so you should be able to rename it if you want. I think the current name is fine too, the "foo-client" convention was from before the advice in `:help dev-api-client` was written :)

**Comment by alexgenco** [comment]
Sounds good, I'll leave it as is for now, since I think `neovim-ruby` is a more descriptive name on its own.
