### ISSUE TITLE
LustyJuggler is rather slow

### ISSUE THREAD

**Issue by comex** [neovim/neovim-ruby#54]
[LustyJuggler](https://github.com/sjbach/lusty) is a Ruby-using Vim plugin for quickly switching buffers.  Using regular Vim, it feels instantaneous.  Using NeoVim, however, it takes about 500ms to complete a switch (measured with pre-buffered keyboard input, starting from when ":LustyJuggler" appears on screen to when the current buffer actually switches).  I tested this using trunk versions of neovim and neovim-ruby, without any debug options on.

The time taken is perhaps not *that* surprising considering that it makes ~4,000 requests.  I tried running under `NVIM_RUBY_LOG_LEVEL='+DEBUG+'`; the full log file is 369MB, but here's just the list of requests:

https://gist.github.com/comex/3998384422fad54bcb5b89979a5115a9

So perhaps I should look into reducing the number of requests.  Still, this is a significant regression compared to classic Vim and makes LustyJuggler practically unusable, so it would be nice to optimize neovim-ruby to the extent possible.

I tried running neovim-ruby-host under ruby-prof.  Here's the output in graph_html mode (for a run doing around 20 buffer switches):

https://gistpreview.github.io/?03256405b11d644a7e5cf3e4e656b714

One hotspot stands out: `Neovim::Client#respond_to_missing?` -> `Neovim::Client#rpc_methods` takes 37.82% of the total time, just to repeatedly calculate a list of available methods for the same client object.  This should be cached, and (though this is more of a nitpick) the code should probably use a Set rather than linearly scanning through an array.

**Comment by alexgenco** [comment]
Great optimization, I'll take a crack at it.

**Comment by alexgenco** [comment]
@comex when you get a chance, can you try `rake install`ing from this PR branch and running your benchmarks? https://github.com/neovim/neovim-ruby/pull/55

**Comment by comex** [comment]
Awesome!  That seems to be even more of a win than ruby-prof would suggest: switch time dropped by more than half, from ~450ms to ~175ms (retesting both versions with a more accurate benchmark). 

For the record, here is the benchmark (I have `0` mapped to launch LustyJuggler):
```
:let start_time = reltime() | call feedkeys(repeat("0s\<CR>", 20) . ":echo reltimefloat(reltime(start_time)) / 20.0\n") 
```

That still leaves room for improvement, though.  I suspect that most of the overhead would go away if LustyJuggler had some way to queue up multiple commands to then be sent in one request.  I think I'll try implementing that on LustyJuggler's side and report back... if I'm right, perhaps neovim-ruby would benefit from having an API for that.

**Comment by alexgenco** [comment]
> some way to queue up multiple commands to then be sent in one request

I'm interested to see how this would look in LustyJuggler. We can expose something in neovim-ruby to buffer certain RPC messages (notifications, maybe client responses?) and then flush them all in one go, but I'm not sure how that would work for client requests, which necessarily block on the response from nvim.

For instance:

```ruby
c = Neovim.attach_unix("/tmp/nvim.sock")

c.buffer do
  c.command("echom 'first'")
  x = c.strwidth("foo") # what happens here?
  c.command("echom '#{x}'")
end
```

Not to mention the fact that neovim-ruby treats all generated methods as blocking right now.

A possible solution would be to abort the `buffer` block with an exception if a synchronous method is called (non-`void` return type). Another would be to just implicitly flush on synchronous methods. I'm just not sure how useful either of these would be though. Anyone else have thoughts?

**Comment by comex** [comment]
Yep, I already made sure logging was off when benchmarking.

**Comment by alexgenco** [comment]
@comex I opened a PR with some quick optimizations https://github.com/neovim/neovim-ruby/pull/58. It brought the `__refresh_globals` method down to a single RPC request (instead of 2-3), which might help a bit.

**Comment by alexgenco** [comment]
Closing for now.
