### ISSUE TITLE
ArgumentError because of a seemingly unrelated line

### ISSUE THREAD

**Issue by mhinz** [neovim/neovim-ruby#59]
Hi,

Today I started playing around with a Ruby rplugin and I'm not really sure if this is a bug or just PEBKAC. Here's a bit of code:

```ruby
require 'net/http'
require 'uri'
require 'json'

class Travis
  def request(options)
    uri = URI('https://api.travis-ci.com/user')

    req = Net::HTTP::Get.new(uri)
    req['Travis-API-Version'] = 3
    req['User-Agent']         = 'testing a script'
    req['Authorization']      = "token #{ENV['TRAVIS_TOKEN']}"

    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http|
      http.request(req)
    }

    if response.is_a?(Net::HTTPForbidden)
      "Access denied. Typo in $TRAVIS_TOKEN?"
    elsif not response.is_a?(Net::HTTPSuccess)
      response.body
    else
      JSON.pretty_generate(JSON.parse(response.body))
    end
  end
end

Neovim.plugin do |plug|
  plug.command(:Travis, nargs: 0) do |nvim|
    travis = Travis.new()
    # response = travis.request()
    nvim.command("echomsg 'blah'")
  end
end
```

When I use `:Travis`, I get the expected "blah". But when I uncomment that one line, I get:

```
Exception handling /Users/mhi/.vim/bundle/nvim-travis/rplugin/ruby/travis.rb:command:Tra
vis: (ArgumentError) wrong number of arguments (given 0, expected 1)
```

Huh? :) I think `Travis#request` is not even run, it fails earlier.

Do you happen to know what's wrong with it?

**Comment by alexgenco** [comment]
I think it's because you are calling `request` with no arguments but it takes a single options argument.

**Comment by mhinz** [comment]
Yes, I'm an idiot. I somehow thought it was coming from this plugin...

![](https://media.giphy.com/media/E2USislQIlsfm/giphy.gif)

Sorry for the noise and thanks for the plugin!

---

... that said, I actually have another question. I could open another PR for it, but I guess it's not really worth it:

How does a Ruby user usually setup their repos for development? E.g. in Python I do `pip3 install -e .` in a package and it gets registered as "edit mode" (opposed to something installed remotely via `pip3 install`)`. Every Python code that now does `import mypackage` now automatically uses my local master branch.

How do you do that in Ruby? How can I hack at this repo and immediately see my changes taking effect? The best I found so far was somehow using `bundler install --binstubs`, but I feel like your system quickly gets clobbered with stub files and it's weird if you switch between repos etc. (Sorry if the answer is obvious to a regular Ruby user!)

**Comment by alexgenco** [comment]
If you run `bundle exec rake install` in your local repo, it will install the package locally as is. But you have to run that after every change I think.
