### ISSUE TITLE
set client info after connecting

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim-ruby#60]
Nvim 0.3.2+ has `nvim_set_client_info` API method, so that clients can provide hints about their identity and purpose.

Example from pynvim https://github.com/neovim/pynvim/pull/350 host (later enhanced in https://github.com/neovim/pynvim/pull/399):

```python
        if len(plugins) == 1 and has_script:
            kind = "script"
        else:
            kind = "rplugin"
        name = "python{}-{}-host".format(sys.version_info[0], kind)
        attributes = {"license": "Apache v2",
                      "website": "github.com/neovim/python-client"}
        self.nvim.api.set_client_info(
            name, VERSION.__dict__, "host", host_method_spec,
            attributes, async_=True)
```

- To keep it easy, neovim-ruby could just omit the "method spec" for now. Something is better than nothing, because then users/plugins can inspect `nvim_list_chans()` or listen to `ChanInfo`/`ChanOpen`.
- ~~Currently pynvim seems to only identify if the "host" is used~~ 
  - Changed in https://github.com/neovim/pynvim/pull/399 . pynvim now sets client info even for the basic (non-host) client.

**Comment by alexgenco** [comment]
Sorry I've been out of town, I'll look into this in the next few days

**Comment by alexgenco** [comment]
@justinmk Not sure if I'm reading this correctly, but is the method spec always hardcoded to "poll", "specs", and "shutdown" even for remote plugin hosts? Looking at this: https://github.com/neovim/pynvim/blob/4dd9962c47bc9d48dc01d7cdf99e3c9819e97548/pynvim/plugin/host.py#L23

**Comment by justinmk** [comment]
@alexgenco for non-host client, pynvim sends `{}` for the method spec. I'm not sure if that should be changed, I didn't think about it much.

**Comment by alexgenco** [comment]
resolved in https://github.com/neovim/neovim-ruby/pull/61

**Comment by alexgenco** [comment]
Forgot to release this until just now: https://rubygems.org/gems/neovim/versions/0.8.1
