### ISSUE TITLE
Get visual selected text

### ISSUE THREAD

**Issue by AlexVKO** [neovim/neovim-ruby#66]
Hi, 

I'm building a plugin that works in visual mode, 

Is there a way to easily get the selected text with ruby? (Inside the plugin block)

Thank you for the great work.

**Comment by alexgenco** [comment]
If you pass `range: true` in the plugin hook it will yield the line numbers selected (1-indexed): https://github.com/neovim/neovim-ruby/blob/898f88db603410da7e461e0833238547f5f18eea/spec/acceptance/runtime/rplugin/ruby/functions.rb#L6-L8

If you want to convert these to the line contents, you can use `nvim.current.buffer.lines[start-1..stop-1]`. Note you have to convert to 0-indexed.

**Comment by AlexVKO** [comment]
Cool, that helps, but what about

![Screen Shot 2020-05-24 at 7 30 42 PM](https://user-images.githubusercontent.com/8848152/82767366-21edc380-9df5-11ea-9f5c-b92eb213ab83.png)

**Comment by alexgenco** [comment]
That's not quite as straightforward! Here's something I came up with that puts the selection into a yank buffer and evaluates it back out:

```ruby
Neovim.plugin do |p|
  p.command(:GetSelected, range: true) do |nvim|
    # Recover visual selection (`gv`), and yank it to the `a` register (`"ay`)
    nvim.command("normal! gv\"ay")

    # Evaluate contents of `a` register
    selection = nvim.evaluate("@a")

    # ...
  end
end
```

Not sure if there's a more straightforward way.
