### ISSUE TITLE
Testing a Ruby plugin

### ISSUE THREAD

**Issue by bweave** [neovim/neovim-ruby#71]
How would I go about setting up testing with Minitest for a Ruby plugin? Did I miss that in the docs somewhere?

Thanks!

**Comment by alexgenco** [comment]
I think you have a couple options here:

1. Write unit-style tests like the ones in neovim-ruby itself: https://github.com/neovim/neovim-ruby/blob/main/spec/neovim/plugin_spec.rb
2. Write more integration-level tests using a vim test suite such as [themis](https://github.com/thinca/vim-themis) or [vspec](https://github.com/kana/vim-vspec). neovim-ruby actually has a [themis test suite](https://github.com/neovim/neovim-ruby/tree/main/spec/acceptance), and [here's a nice vimcast on vspec](http://vimcasts.org/episodes/an-introduction-to-vspec/).

If you come up with any ideas for utilities in neovim-ruby itself to facilitate testing, feel free to report back. This is the first time it has come up!

**Comment by bweave** [comment]
For anyone else who might find it useful, I ended up extracting the bits I care about testing out into a class and calling that class from the `Nvim.plugin` call. You can check it out here: https://github.com/bweave/nvim-plugins. ❤️  that I can skip the Vimscript and create the functionality I want/need in the language I love!
