### ISSUE TITLE
$NVIM_LISTEN_ADDRESS will be removed

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim-ruby#82]
I don't see $NVIM_LISTEN_ADDRESS being used in this repo but just want to make sure, because I noticed ruby provider failing in https://github.com/neovim/neovim/pull/11009 (but I haven't root-caused that yet).

https://github.com/neovim/neovim/pull/11009 (Nvim 0.8+) will change Nvim so that $NVIM_LISTEN_ADDRESS is _not_ passed to child processes.  After that, the correct way to detect a "host" or "parent" Nvim is to check for $NVIM env var: this means the current process is a child of Nvim.

The old $NVIM_LISTEN_ADDRESS env var had conflicting purposes as both a parameter ("the current process should _listen on_ this address") and a descriptor ("the current process is a _child of_ this address").

Related change in Nvim node-client: https://github.com/neovim/node-client/pull/195

**Comment by alexgenco** [comment]
Thanks for the info. I can check out that build failure and update the documentation a little later, but yeah this library doesn't use that env var directly. I actually never knew it was also meant to be used as an indicator of whether the current process was spawned by nvim; that isn't a concept this library cares about currently.

**Comment by alexgenco** [comment]
This removes the references in documentation: https://github.com/neovim/neovim-ruby/pull/83

I didn't find any Ruby provider failures on that PR build, could you link me to them if they're still happening?

**Comment by justinmk** [comment]
> I didn't find any Ruby provider failures on that PR build, could you link me to them if they're still happening?

They're gone, the issue was unrelated to this.
