### ISSUE TITLE
Error when triggering a Ruby plugin: "Error detected while processing function remote#define#notify:"

### ISSUE THREAD

**Issue by hboon** [neovim/neovim-ruby#94]
> Error detected while processing function remote#define#notify:
> line    6:
> E475: Invalid argument: Channel doesn't exist

The plugin is really simple, but at this point, even a simple plug (in the same `.rb` file) like this triggers the error:

```
require 'neovim'

Neovim.plugin do |plug|
  last_check = nil
  plug.command(:Foo) do |nvim|
    if last_check.nil? or Time.new - last_check > 60 
      begin
        nvim.set_var "f", "foobar2"
      rescue Exception
      end
      last_check = Time.new
    end
  end
end
```

Other non-ruby plugins appear to continue to work.

I'm not sure where to look or debug this. It works until this error starts showing and I restart Neovim at this point. I might be missing something fundamental?

Update: I'm running nvim v0.8.3 in Alacritty 0.11.0 (1) on macOS 13.2. Just a single Alacritty instance with a single window, running only nvim.

**Comment by alexgenco** [comment]
Hello, here are a couple things to help diagnose:

- Output of `:checkhealth` command, specifically the `Ruby provider` section
- Output of debug logs, start nvim with: 

```sh
NVIM_RUBY_LOG_FILE=/tmp/nvim_ruby.log NVIM_RUBY_LOG_LEVEL=debug nvim
```

and look at what is written to `/tmp/nvim_ruby.log` when you run `:Foo`
- Make sure you have run `:UpdateRemotePlugins` recently.

**Comment by hboon** [comment]
Thanks. I hit it again after about 1-2 hours usage and the last 2 lines that might be relevant are these:

```
{"_level":"DEBUG","_time":"2023-03-03T09:28:36.848465","_class":"Neovim::EventLoop","_method":"run","exception":"EOFError","message":"end of file reached"}
{"_level":"DEBUG","_time":"2023-03-03T09:28:36.848579","_class":"Neovim::EventLoop","_method":"run","exception":"EOFError","message":"end of file reached","backtrace":["/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/connection.rb:47:in `readpartial'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/connection.rb:47:in `read'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/connection.rb:47:in `read'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/event_loop.rb:109:in `read'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/event_loop.rb:80:in `block in run'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/event_loop.rb:75:in `loop'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/event_loop.rb:75:in `run'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/session.rb:35:in `run'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/host.rb:29:in `run'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/host.rb:17:in `run'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/lib/neovim/host/cli.rb:33:in `run'","/Users/hboon/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/neovim-0.9.0/exe/neovim-ruby-host:5:in `<top (required)>'","/Users/hboon/.asdf/installs/ruby/3.0.3/bin/neovim-ruby-host:25:in `load'","/Users/hboon/.asdf/installs/ruby/3.0.3/bin/neovim-ruby-host:25:in `<main>'"]}
```

When I run the plugin again at this state, no lines are appended to `nvim_ruby.log`.

I run `:UpdateRemotePlugins` a couple of times while I was debugging previously. Running it again after this error doesn't fix it either.

`:checkhealth` output is the same right after I launched nvim as well as right after the error occurs:

```
## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin22]
  - INFO: Host: /Users/hboon/.asdf/shims/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.9.0
```

Running `:ruby print 3+4` in command-line mode/area prints `7`.

`:rubyfile` seems OK too

**Comment by alexgenco** [comment]
What version of neovim are you on?

Can you reproduce with just the one plugin loaded and starting vim with `nvim -u NORC`? You'll have to move any other plugins out of `~/.config/nvim/rplugin/*`.

FWIW I think that EOF is only expected to happen when nvim shuts down the rpc stream.

**Comment by hboon** [comment]
> Can you reproduce with just the one plugin loaded and starting vim with nvim -u NORC? You'll have to move any other plugins out of ~/.config/nvim/rplugin/*.

I only have that 1 ruby plugin. Will try that. Thanks.

Have updated first comment to say this too. Sorry, forgot: I'm running nvim v0.8.3 in Alacritty 0.11.0 (1) on macOS 13.2. Just a single Alacritty instance with a single window, running only nvim.

**Comment by hboon** [comment]
What they say about every bug reporter lying? That's true. I'm sorry.

Here's how I can reproduce it reliably the first time now:

```
require 'neovim'

Neovim.plugin do |plug|
  plug.command(:CreateIssue) do |nvim|
    begin
      cmd = "gh issue create --body \"body\" --title \"title 2\" --repo \"https://github.com/hboon/test2\""

      system(cmd)
    rescue Exception => e
      nvim.set_var "f1", "exception: #{e}"
    end
  end
end
```

You'll want to have `gh` (the GitHub cli installed) and modify the URL about to a throwaway repo you have access to:

1. Run a new nvim instance
2. Run in commandline mode: `CreateIssue`
3. Run in commandline mode: `CreateIssue` #this will show the error

I kept the code to call `gh` because if I switch it to only `system("open https://github.com/hboon/test2/issues/")`, there appears to be no problem. Maybe the difference is it takes a while longer for the call to return?

Is there something I should do instead of calling `system`?

**Comment by hboon** [comment]
(`:CreateIssue` is meant to read the current file and create an issue in a hardcoded repo I work most often with)

**Comment by alexgenco** [comment]
Ah I see what's happening. `gh` writes to stdout:

```
% gh issue create --body "test" --title "testing" --repo https://github.com/alexgenco/test                                                                                                                                                                                 

Creating issue in alexgenco/test

https://github.com/alexgenco/test/issues/1
```

The nvim ruby host communicates with nvim via stdout, and since `system` inherits the parent stdout, nvim is trying to interpret that output as a msgpack rpc message.

This should fix your error:

```
system(cmd, [:out, :err] => File::NULL)
```

This feels like a bit of a landmine, so I'll think if there are ways to avoid this. But this should unblock you for now.

**Comment by hboon** [comment]
Works for me. Thanks a lot.
